# Generated by Django 5.1.6 on 2025-03-07 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='last_attempt_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('challenges_completed', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', 'ranking'],
            },
        ),
    ]
